# Generated by Django 3.0.8 on 2020-07-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=122)),
                ('Email', models.EmailField(max_length=122)),
                ('Subject', models.CharField(max_length=122)),
                ('Message', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
