# Generated by Django 3.0.8 on 2020-07-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200726_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TimeField(max_length=255)),
                ('content', models.TimeField(max_length=350)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
